# Generated by Django 4.2.1 on 2023-06-02 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contact_website_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='website_title',
            field=models.TextField(default='asa'),
            preserve_default=False,
        ),
    ]
