# Generated by Django 4.2.1 on 2023-06-03 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_contact_website_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='homebarner',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='homebarner',
            name='text_position',
            field=models.CharField(choices=[('text-center', 'text-center'), ('text-right', 'text-right'), ('text-left', 'text-left')], default='text-center', max_length=255),
        ),
    ]
