# Generated by Django 4.2.1 on 2023-06-05 12:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_linkedin_contact_whatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectitem',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
